Tablaperiodica={
    "1":{
        "Símbolo": "H",
        "Nombre": "Hidrógeno",
        "Número atómico": "1",
        "Peso atómico": "1,00794",
        "Grupo": "IA",
        "Periodo": "1",
        "Configuración electrónica": "1s1"},
    "2":{
        "Símbolo": "He",
        "Nombre": "Helio",
        "Número atómico": "2",
        "Peso atómico": "4,002602",
        "Grupo": "VIIIA",
        "Periodo": "1",
        "Configuración electrónica": "1s2"},
    "3":{
        "Símbolo": "Li",
        "Nombre": "Litio",
        "Número atómico": "3",
        "Peso atómico": "6,941",
        "Grupo": "IA",
        "Periodo": "2",
        "Configuración electrónica": "1s2, 2s1"},
    "4":{
        "Símbolo": "Be",
        "Nombre": "Berilio",
        "Número atómico": "4",
        "Peso atómico": "9,012182",
        "Grupo": "IIA",
        "Periodo": "2",
        "Configuración electrónica": "1s2, 2s2"},
    "5":{
        "Símbolo": "B",
        "Nombre": "Boro",
        "Número atómico": "5",
        "Peso atómico": "10,811",
        "Grupo": "IIIA",
        "Periodo": "2",
        "Configuración electrónica": "1s2,2s2,2p1"},
    "6":{
        "Símbolo": "C",
        "Nombre": "Carbono",
        "Número atómico": "6",
        "Peso atómico": "12,0107",
        "Grupo": "IVA",
        "Periodo": "2",
        "Configuración electrónica": "1s2,2s2,2p2"},
    "7":{
        "Símbolo": "N",
        "Nombre": "Nitrógeno",
        "Número atómico": "7",
        "Peso atómico": "14,0067",
        "Grupo": "VA",
        "Periodo": "2",
        "Configuración electrónica": "1s2,2s2,2p3"},
    "8":{
        "Símbolo": "O",
        "Nombre": "Oxígeno",
        "Número atómico": "8",
        "Peso atómico": "15,9994",
        "Grupo": "VIA",
        "Periodo": "2",
        "Configuración electrónica": "1s2,2s2,2p4"},
    "9":{
        "Símbolo": "F",
        "Nombre": "Flúor",
        "Número atómico": "9",
        "Peso atómico": "18,998403",
        "Grupo": "VIIA",
        "Periodo": "2",
        "Configuración electrónica": "1s2,2s2,2p5"},
    "10":{
        "Símbolo": "Ne",
        "Nombre": "Neón",
        "Número atómico": "10",
        "Peso atómico": "20,1797",
        "Grupo": "VIIIA",
        "Periodo": "2",
        "Configuración electrónica": "1s2,2s2,2p6"},
    "11":{
        "Símbolo": "Na",
        "Nombre": "Sodio",
        "Número atómico": "11",
        "Peso atómico": "22,98976",
        "Grupo": "IIIA",
        "Periodo": "2",
        "Configuración electrónica": "3s1"},
    "12":{
        "Símbolo": "Mg",
        "Nombre": "Magnesio",
        "Número atómico": "12",
        "Peso atómico": "24,3050",
        "Grupo": "IVA",
        "Periodo": "2",
        "Configuración electrónica": "3s2"},
    "13":{
        "Símbolo": "Al",
        "Nombre": "Aluminio",
        "Número atómico": "13",
        "Peso atómico": "26,98153",
        "Grupo": "IIIA",
        "Periodo": "3",
        "Configuración electrónica": "3s2,3p1"},
    "14":{
        "Símbolo": "Si",
        "Nombre": "Silicio",
        "Número atómico": "12",
        "Peso atómico": "28,0855",
        "Grupo": "IVA",
        "Periodo": "3",
        "Configuración electrónica": "3s2,3p2"},
    "15":{
        "Símbolo": "P",
        "Nombre": "Potasio",
        "Número atómico": "15",
        "Peso atómico": "30,97696",
        "Grupo": "VA",
        "Periodo": "3",
        "Configuración electrónica": "3s2,3p3"},
    "16":{
        "Símbolo": "S",
        "Nombre": "Azufre",
        "Número atómico": "16",
        "Peso atómico": "32,065",
        "Grupo": "VIA",
        "Periodo": "3",
        "Configuración electrónica": "3s2,3p4"},
    "17":{
        "Símbolo": "Cl",
        "Nombre": "Cloro",
        "Número atómico": "17",
        "Peso atómico": "35,453",
        "Grupo": "VIIA",
        "Periodo": "3",
        "Configuración electrónica": "3s2,3p5"},
    "18":{
        "Símbolo": "Ar",
        "Nombre": "Argón",
        "Número atómico": "18",
        "Peso atómico": "39,948",
        "Grupo": "VIIIA",
        "Periodo": "3",
        "Configuración electrónica": "3s2,3p6"},
    "19":{
        "Símbolo": "K",
        "Nombre": "Potasio",
        "Número atómico": "19",
        "Peso atómico": "39,0983",
        "Grupo": "VA",
        "Periodo": "2",
        "Configuración electrónica": "4s1"},
    "20":{
        "Símbolo": "Ca",
        "Nombre": "Calcio",
        "Número atómico": "20",
        "Peso atómico": "40,078",
        "Grupo": "IIA",
        "Periodo": "4",
        "Configuración electrónica": "4s2"},
    "31":{
        "Símbolo": "Ga",
        "Nombre": "Galio",
        "Número atómico": "31",
        "Peso atómico": "69,723",
        "Grupo": "IIIA",
        "Periodo": "4",
        "Configuración electrónica": "3d10,4s2,4p1"},
    "32":{
        "Símbolo": "Ge",
        "Nombre": "Germanio",
        "Número atómico": "32",
        "Peso atómico": "72,64",
        "Grupo": "IVA",
        "Periodo": "4",
        "Configuración electrónica": "3d10,4s2,4p2"},
    "33":{
        "Símbolo": "As",
        "Nombre": "Arsénico",
        "Número atómico": "33",
        "Peso atómico": "74,92160",
        "Grupo": "VA",
        "Periodo": "4",
        "Configuración electrónica": "3d10,4s2,4p3"},
    "34":{
        "Símbolo": "Se",
        "Nombre": "Selenio",
        "Número atómico": "34",
        "Peso atómico": "78,96",
        "Grupo": "VIA",
        "Periodo": "4",
        "Configuración electrónica": "3d10,4s2,4p4"},
    "35":{
        "Símbolo": "Br",
        "Nombre": "Bromo",
        "Número atómico": "35",
        "Peso atómico": "79,904",
        "Grupo": "VIA",
        "Periodo": "4",
        "Configuración electrónica": "3d10,4s2,4p5"},
    "36":{
        "Símbolo": "Kr",
        "Nombre": "Kriptón",
        "Número atómico": "36",
        "Peso atómico": "83,798",
        "Grupo": "VIIA",
        "Periodo": "4",
        "Configuración electrónica": "3d10,4s2,4p6"},
    "37":{
        "Símbolo": "Rb",
        "Nombre": "Rubidio",
        "Número atómico": "37",
        "Peso atómico": "85,4678",
        "Grupo": "IA",
        "Periodo": "5",
        "Configuración electrónica": "5s1"},
    "38":{
        "Símbolo": "Sr",
        "Nombre": "Estroncio",
        "Número atómico": "38",
        "Peso atómico": "87,62",
        "Grupo": "IIA",
        "Periodo": "5",
        "Configuración electrónica": "5s2"},
    "49":{
        "Símbolo": "In",
        "Nombre": "Indio",
        "Número atómico": "49",
        "Peso atómico": "114,818",
        "Grupo": "IIIA",
        "Periodo": "5",
        "Configuración electrónica": "4d10,5s2,5p1"},
    "50":{
        "Símbolo": "Sn",
        "Nombre": "Estaño",
        "Número atómico": "50",
        "Peso atómico": "118,710",
        "Grupo": "IVA",
        "Periodo": "5",
        "Configuración electrónica": "4d10,5s2,5p2"},
    "51":{
        "Símbolo": "Sb",
        "Nombre": "Antimonio",
        "Número atómico": "51",
        "Peso atómico": "121,760",
        "Grupo": "VA",
        "Periodo": "5",
        "Configuración electrónica": "4d10,5s2,5p3"},
    "52":{
        "Símbolo": "Te",
        "Nombre": "Telurio",
        "Número atómico": "52",
        "Peso atómico": "127,60",
        "Grupo": "VIA",
        "Periodo": "5",
        "Configuración electrónica": "4d10,5s2,5p4"},
    "53":{
        "Símbolo": "I",
        "Nombre": "Yodo",
        "Número atómico": "53",
        "Peso atómico": "126,9044",
        "Grupo": "VIIA",
        "Periodo": "5",
        "Configuración electrónica": "4d10,5s2,5p5"},
    "54":{
        "Símbolo": "Xe",
        "Nombre": "Xenón",
        "Número atómico": "54",
        "Peso atómico": "131,293",
        "Grupo": "VIIIA",
        "Periodo": "5",
        "Configuración electrónica": "4d10,5s2,5p6"},
    "55":{
        "Símbolo": "Cs",
        "Nombre": "Cesio",
        "Número atómico": "55",
        "Peso atómico": "132,9054",
        "Grupo": "IA",
        "Periodo": "6",
        "Configuración electrónica": "6s1"},
    "56":{
        "Símbolo": "Ba",
        "Nombre": "Bario",
        "Número atómico": "56",
        "Peso atómico": "137,327",
        "Grupo": "IIA",
        "Periodo": "6",
        "Configuración electrónica": "6s2"},
    "81":{
        "Símbolo": "Tl",
        "Nombre": "Talio",
        "Número atómico": "81",
        "Peso atómico": "204,3833",
        "Grupo": "IIIA",
        "Periodo": "6",
        "Configuración electrónica": "4f14,5d10,6s2,6p1"},
    "82":{
        "Símbolo": "Pb",
        "Nombre": "Plomo",
        "Número atómico": "82",
        "Peso atómico": "207,2",
        "Grupo": "IVA",
        "Periodo": "6",
        "Configuración electrónica": "4f14,5d10,6s2,6p2"},
    "83":{
        "Símbolo": "Bi",
        "Nombre": "Bismuto",
        "Número atómico": "83",
        "Peso atómico": "208,9804",
        "Grupo": "VA",
        "Periodo": "6",
        "Configuración electrónica": "4f14,5d10,6s2,6p3"},
    "84":{
        "Símbolo": "Po",
        "Nombre": "Polonio",
        "Número atómico": "84",
        "Peso atómico": "210",
        "Grupo": "VIA",
        "Periodo": "6",
        "Configuración electrónica": "4f14,5d10,6s2,6p4"},
    "85":{
        "Símbolo": "At",
        "Nombre": "Astato",
        "Número atómico": "85",
        "Peso atómico": "210",
        "Grupo": "VIIA",
        "Periodo": "6",
        "Configuración electrónica": "4f14,5d10,6s2,6p5"},
    "86":{
        "Símbolo": "Rn",
        "Nombre": "Radón",
        "Número atómico": "86",
        "Peso atómico": "220",
        "Grupo": "VIIIA",
        "Periodo": "6",
        "Configuración electrónica": "4f14,5d10,6s2,6p6"},
    "87":{
        "Símbolo": "Fr",
        "Nombre": "Francio",
        "Número atómico": "87",
        "Peso atómico": "223",
        "Grupo": "IA",
        "Periodo": "7",
        "Configuración electrónica": "7s1"},
    "88":{
        "Símbolo": "Ra",
        "Nombre": "Radio",
        "Número atómico": "88",
        "Peso atómico": "226",
        "Grupo": "IIA",
        "Periodo": "7",
        "Configuración electrónica": "7s2"},
    "113":{
        "Símbolo": "Nh",
        "Nombre": "Nihonio",
        "Número atómico": "113",
        "Peso atómico": "284",
        "Grupo": "IIIA",
        "Periodo": "7",
        "Configuración electrónica": "5f14,6d10,7s2,7p1"},
    "114":{
        "Símbolo": "Fl",
        "Nombre": "Flerovio",
        "Número atómico": "114",
        "Peso atómico": "289",
        "Grupo": "IVA",
        "Periodo": "7",
        "Configuración electrónica": "5f14,6d10,7s2,7p2"},
    "115":{
        "Símbolo": "Mc",
        "Nombre": "Moscovio",
        "Número atómico": "115",
        "Peso atómico": "288",
        "Grupo": "VA",
        "Periodo": "7",
        "Configuración electrónica": "5f14,6d10,7s2,7p3"},
    "116":{
        "Símbolo": "Lv",
        "Nombre": "Livermorio",
        "Número atómico": "116",
        "Peso atómico": "292",
        "Grupo": "VIA",
        "Periodo": "7",
        "Configuración electrónica": "5f14,6d10,7s2,7p4"},
    "117":{
        "Símbolo": "Ts",
        "Nombre": "Tenesio",
        "Número atómico": "117",
        "Peso atómico": "294",
        "Grupo": "VIIA",
        "Periodo": "7",
        "Configuración electrónica": "5f14,6d10,7s2,7p5"},
    "118":{
        "Símbolo": "Og",
        "Nombre": "Oganesón",
        "Número atómico": "118",
        "Peso atómico": "294",
        "Grupo": "VIIIA",
        "Periodo": "7",
        "Configuración electrónica": "5f14,6d10,7s2,7p6"},
        }
print(Tablaperiodica)